name: ✨ Feature Request
description: Suggest a new feature or improvement.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out the form below to help us better understand your idea.
  - type: input
    id: summary
    attributes:
      label: Brief Summary
      description: Provide a short summary of the proposed feature (1-2 sentences).
      placeholder: Summarize your idea briefly.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem This Feature Solves
      description: Describe the problem or need that the proposed feature addresses.
      placeholder: What problem or need does this feature solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how the feature should work. Include implementation details if possible.
      placeholder: What is your proposed solution?
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Explain how this feature will improve the project or help users.
      placeholder: What are the benefits of implementing this feature?
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low
        - Medium
        - High
      default: 0
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: "Confirm you have checked the following:"
      options:
        - label: I have searched for similar feature requests in the repository.
        - label: I have included all necessary details to describe this feature.
    validations:
      required: true
