name: Create release

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Automated Version ${{ github.event.inputs.release_type || 'patch' }}
        uses: 'phips28/gh-action-bump-version@master'
        id: version-bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: "main"
          default: ${{ github.event.inputs.release_type || 'patch' }}
          commit-message: "CI: bumps version to {{version}}"
          minor-wording: 'add,Adds,new,added'
          major-wording: 'MAJOR,cut-major'
          patch-wording: 'patch,fixes,fixed,fix'
          rc-wording: 'RELEASE,alpha'

  release:
    needs:
      - build
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Version
        run: |
          echo "MPRGS_VERSION=$(grep -oP -m 1 '(?<=")(?:\\.|[^"\\])*(?=")' project.clj)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.MPRGS_VERSION }}"
          prerelease: true
          title: "Node-Red-ESPHome Release v${{ env.MPRGS_VERSION }}"
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          automatic_release_tag: "latest"
#          prerelease: true
#          title: Node-Red-ESPHome Release
          files: release.zip

