name: Check branch name

on:
  push:
    branches: [ main ]

permissions:
  contents: writel

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Build Project
        run: bun run build

      - uses: vimtor/action-zip@v1.2
        with:
          files: dist/ package.json
          dest: release.zip

      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: Node-Red-ESPHome Release
          files: release.zip

