name: Check branch name

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Automated Version ${{ github.event.inputs.release_type || 'patch' }}
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: "main"
          default: ${{ github.event.inputs.release_type || 'patch' }}
          commit-message: "CI: bumps version to {{version}}"
          minor-wording: 'add,Adds,new,added'
          major-wording: 'MAJOR,cut-major'
          patch-wording: 'patch,fixes,fixed,fix'
          rc-wording: 'RELEASE,alpha'
